name: CI/CD Pipeline task-2

on:
  push:
    branches:
      - task-2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Package app
        run: zip -r app.zip server.js package.json package-lock.json .eslintrc.json

      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.zip"
          target: "/home/ec2-user/"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            pm2 delete all || true
            sudo fuser -k 3000/tcp || true
            sudo rm -rf app
            unzip -o app.zip -d app
            cd app
            npm install -f
            npm set-script start "node server.js"
            pm2 start npm --name node-app -- start
            pm2 save
